services:
  frontend:
    restart: "no"
  identifier:
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    restart: "no"
    environment:
      ENABLE_CORS: "true"
  login:
    restart: "no"
  resource:
    restart: "no"
  cache:
    restart: "no"
  deltanotifier:
    restart: "no"
  migrations:
    restart: "no"
  mocklogin:
    image: lblod/mock-login-service:latest
  sparql-cache:
    restart: "no"
  publisher:
    restart: "no"
  file:
    restart: "no"
  tlsproxy:
    image: caddy:2
    environment:
      SITE_ADDRESS: "reglementairebijlagen.lblod.info"
    volumes:
      - ./config/dev/tlsproxy/Caddyfile:/etc/caddy/Caddyfile
  codex-proxy:
    restart: "no"
  template-export:
    restart: "no"
