# This file contains overrides that are useful for different development situations. These are
# intended to be used at the same time as the docker-compose.dev.yml file.

# services:
  ### Local dev setup: tweaks to .dev.yml to allow for running side-by-side with app-gn
  # identifier:
  #   ports: !override
  #     - "180:80"
  # virtuoso:
  #   ports: !override
  #     - "9890:8890"
  # yasgui:
  #   image: erikap/yasgui
  #   ports: !override
  #     - "9891:80"
  #   environment:
  #     ENABLE_ENDPOINT_SELECTOR: "true"
  #     DEFAULT_SPARQL_ENDPOINT: "http://localhost:9890/sparql"
  # tlsproxy:
  #   image: caddy:2
  #   command: "/bin/false"
  #   ports: !reset null
  ### END local dev setup

  # Actually running template-export service before it's published to docker hub
  # template-export:
  #   image: !reset null
  #   build: "https://github.com/lblod/template-export-service.git#feat/initial-version"
  #   volumes:
  #     - /path/to/template-export-service:/app
  #   # environment:
  #   #   NODE_ENV: development
  #   #   LOGGING_LEVEL: "debug"
  #   #   LOG_SPARQL_ALL: false
  #   #   DEBUG_AUTH_HEADERS: false
  #   # ports:
  #   #   - "9229:9229"
