PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
INSERT {
  GRAPH ?g {
        ?concept ext:summary "".
  }
}
WHERE {
  GRAPH ?graph {
    ?concept a skos:Concept;
  } 
  BIND(?graph as ?g)
}