PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX schema: <http://schema.org/>
PREFIX gn: <http://data.lblod.info/vocabularies/gelinktnotuleren/>

DELETE {
  GRAPH ?g {
    ?snippetList a ext:SnippetList.
  }
}
INSERT {
  GRAPH ?g {
    ?snippetList a gn:SnippetList.
  }
}
WHERE {
  GRAPH ?g {
    ?snippetList a ext:SnippetList.
  }
};


DELETE {
  GRAPH ?g {
    ?snippet a ext:PublishedSnippetContainer.
    ?snippet prov:derivedFrom ?derivedFrom.
    ?snippet ext:fromSnippetList ?snippetList.
  }
}
INSERT {
  GRAPH ?g {
    ?snippet a gn:Snippet.
    ?snippetList gn:hasSnippet ?snippet.
  }
}
WHERE {
  GRAPH ?g {
    ?snippet a ext:PublishedSnippetContainer.
    ?snippet prov:derivedFrom ?derivedFrom.
    OPTIONAL {
      ?snippet ext:fromSnippetList ?snippetList.
    }
  }
};

DELETE {
  GRAPH ?g {

  }
}
INSERT {
  GRAPH ?g {

  }
}
WHERE {
  GRAPH ?g {
    ?snippetVersion a ext:PublishedSnippet.
    ?snippetVersion prov:derivedFrom ?derivedFrom.
  }
}